# Generated by Django 4.1.7 on 2023-03-31 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('CORETE', 'Corte'), ('MODELAGEM', 'Modelagem'), ('COSTURA', 'Costura'), ('OUTROS', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='thumb',
            field=models.ImageField(upload_to='thumb_cursos'),
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='curso.curso')),
            ],
        ),
    ]
